export type SourceKind = "YouTube" | "X" | "Newsletter" | "Blog";

export type SourceItem = {
  id: number;
  name: string;
  description: string;
  url: string;
  feedUrl?: string;
};

export function getSourceKind(url: string): SourceKind {
  const host = new URL(url).hostname;
  if (host.includes("youtube.com")) return "YouTube";
  if (host === "x.com") return "X";
  if (host.includes("substack.com")) return "Newsletter";
  return "Blog";
}

export const sourceCatalog: SourceItem[] = [
  { id: 1, name: "Lex Fridman Podcast", description: "与科学家、工程师、哲学家和世界领袖的深度长对话。", url: "https://www.youtube.com/channel/UCSHZKyawb77ixDdsGog4iWA" },
  { id: 2, name: "Decoder", description: "The Verge 旗下播客，聚焦科技领袖如何做出重大决策。", url: "https://www.youtube.com/channel/UCddiUEpeqJcYeBxX1IVBKvQ" },
  { id: 3, name: "Y Combinator", description: "全球顶级加速器（Airbnb、Stripe、Dropbox），提供免费创业课程和创始人演讲。", url: "https://www.youtube.com/channel/UCcefcZRL2oaA_uBNeo5UOWg" },
  { id: 4, name: "Two Minute Papers", description: "维也纳工大研究员将前沿 AI 论文浓缩为 2-5 分钟视频，追踪 AI 研究突破最高效的方式。", url: "https://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg" },
  { id: 5, name: "Andrej Karpathy", description: "前特斯拉 AI 总监、OpenAI 联合创始人，其“从零构建 GPT”系列是理解大模型架构的金标准。", url: "https://www.youtube.com/channel/UCXUPKJO5MZQN11PqgIvyuvQ" },
  { id: 6, name: "All-In Podcast", description: "四位硅谷科技投资人每周辩论经济、政治和科技热点话题。", url: "https://www.youtube.com/channel/UCESLZhusAkFfsNsApnjF_Cg" },
  { id: 7, name: "My First Million", description: "Sam Parr 和 Shaan Puri 主持，风格轻松但商业洞察密度高，善于发现非共识商业机会。", url: "https://www.youtube.com/channel/UCyaN6mg5u8Cjy2ZI4ikWaug" },
  { id: 8, name: "ARK Invest", description: "Cathie Wood 官方频道，前联博全球主题投资 CIO，专注颠覆性创新的深度研究。", url: "https://www.youtube.com/channel/UCK-zlnUfoDHzUwXcbddtnkg" },
  { id: 9, name: "DeepLearning.AI", description: "Andrew Ng 创办，提供结构化 AI 课程和行业专家访谈。", url: "https://www.youtube.com/channel/UCcIXc5mJsHVYTZR1maL5l9w" },
  { id: 10, name: "Lenny's Podcast", description: "顶级产品管理播客，汇集行业领袖的增长策略和创业建议。", url: "https://www.youtube.com/channel/UC6t1O76G0jYXOAoYCm153dA" },
  { id: 11, name: "AI Explained", description: "专注大模型进展、AGI 争论和 AI 基准测试分析，信噪比极高。", url: "https://www.youtube.com/channel/UCNJ1Ymd5yFuUPtn21xtRbbw" },
  { id: 12, name: "This Week in Startups", description: "天使投资人 Jason Calacanis 主持，每周多期，以犀利提问著称。", url: "https://www.youtube.com/channel/UCkkhmBWfS7pILYIk0izkc3A" },
  { id: 13, name: "Yannic Kilcher", description: "苏黎世联邦理工博士，深入解读高难度机器学习论文。", url: "https://www.youtube.com/channel/UCZHmQk67mSJgfCCTn7xBfew" },
  { id: 14, name: "Acquired", description: "深度剖析全球最伟大公司背后的故事与战略，内容扎实且信息密度极高。", url: "https://www.youtube.com/channel/UCyFqFYfTW2VoIQKylJ04Rtw" },
  { id: 15, name: "Pivot", description: "Kara Swisher 和 Scott Galloway 每周犀利辩论科技、商业和政治。", url: "https://www.youtube.com/channel/UCBHGZpDF2fsqPIPi0pNyuTg" },
  { id: 16, name: "The Twenty Minute VC (20VC)", description: "Harry Stebbings 采访顶级风投和创始人，聚焦创业投资和企业扩张。", url: "https://www.youtube.com/channel/UCf0PBRjhf0rF8fWBIxTuoWA" },
  { id: 17, name: "SaaStr Podcast (YT)", description: "B2B SaaS 行业洞察，包括创始人故事、关键指标和增长策略。", url: "https://www.youtube.com/channel/UCwOILzAcxK5CM2M7oRBuWSg" },
  { id: 18, name: "RobWalling", description: "Micro-SaaS 与独立开发者、SaaS 创业相关的实战资源。", url: "https://www.youtube.com/channel/UCHoBKQDRkJcOY2BO47q5Ruw" },
  { id: 19, name: "No Priors", description: "硅谷顶级投资人和技术专家主持的 AI 和科技深度讨论。", url: "https://www.youtube.com/channel/UCSI7h9hydQ40K5MJHnCrQvw" },
  { id: 20, name: "Dwarkesh Podcast", description: "与 AI 研究者、历史学家和顶尖知识分子的深度长对话。", url: "https://www.youtube.com/channel/UCXl4i9dYBrFOabk0xGmbkRA" },
  { id: 21, name: "Latent Space", description: "AI 工程师播客，覆盖 AI 开发工具、基础设施和最新技术趋势。", url: "https://www.youtube.com/channel/UCxBcwypKK-W3GHd_RZ9FZrQ" },
  { id: 22, name: "Cognitive Revolution", description: "聚焦 AI 前沿的播客，探索人工智能最新研究和应用。", url: "https://www.youtube.com/channel/UCjNRVMBVI30Sak_p6HRWhIA" },
  { id: 23, name: "a16z", description: "a16z 风投官方频道，聚焦科技行业洞察、创始人访谈和风险投资趋势。", url: "https://www.youtube.com/channel/UC9cn0TuPq4dnbTY-CBsm8XA" },
  { id: 24, name: "Sam Altman", description: "OpenAI CEO，分享 AI 进展、安全和科技行业未来的观点。", url: "https://x.com/sama" },
  { id: 25, name: "Aaron Levie", description: "Box CEO，分享关于企业科技、AI 和未来工作方式的犀利观点。", url: "https://x.com/levie" },
  { id: 26, name: "Andrej Karpathy", description: "前特斯拉 AI 总监、OpenAI 创始成员，深度学习和 AI 教育领域的标杆人物。", url: "https://x.com/karpathy" },
  { id: 27, name: "Claude", description: "Anthropic AI 助手 Claude 的官方账号，发布产品更新和公告。", url: "https://x.com/claudeai" },
  { id: 28, name: "Garry Tan", description: "Y Combinator 总裁兼 CEO，分享创业智慧和风投洞察。", url: "https://x.com/garrytan" },
  { id: 29, name: "Peter Steinberger", description: "PSPDFKit 创始人、iOS 专家，分享开发工具和工程洞察。", url: "https://x.com/steipete" },
  { id: 30, name: "Amjad Masad", description: "Replit CEO，推动 AI 驱动的软件开发和编程民主化。", url: "https://x.com/amasad" },
  { id: 31, name: "Guillermo Rauch", description: "Vercel CEO、Next.js 创始人，聚焦 Web 开发、AI 和开发者体验。", url: "https://x.com/rauchg" },
  { id: 32, name: "Google Labs", description: "Google 实验性 AI 产品、功能和前沿研究演示。", url: "https://x.com/GoogleLabs" },
  { id: 33, name: "Peter Yang", description: "产品管理意见领袖，分享 PM 职业建议和行业洞察。", url: "https://x.com/petergyang" },
  { id: 34, name: "Thariq", description: "AI 研究者，分享机器学习洞察和科技评论。", url: "https://x.com/trq212" },
  { id: 35, name: "Swyx", description: "AI 工程师、Latent Space 播客主持人，AI 领域的知名开发者布道师。", url: "https://x.com/swyx" },
  { id: 36, name: "Matt Turck", description: "FirstMark Capital 合伙人，以年度 MAD（ML/AI/Data）全景图闻名。", url: "https://x.com/mattturck" },
  { id: 37, name: "Alex Albert", description: "Anthropic 提示工程负责人，分享 AI 研究和 Claude 相关洞察。", url: "https://x.com/alexalbert__" },
  { id: 38, name: "Kevin Weil", description: "OpenAI 首席产品官，分享产品愿景和 AI 行业观点。", url: "https://x.com/kevinweil" },
  { id: 39, name: "Dan Shipper", description: "Every CEO，探索 AI 工具如何变革知识工作和创作流程。", url: "https://x.com/danshipper" },
  { id: 40, name: "Amanda Askell", description: "Anthropic 研究员，专注 AI 对齐、哲学和语言模型行为研究。", url: "https://x.com/AmandaAskell" },
  { id: 41, name: "Josh Woodward", description: "Google Labs VP，分享 AI 产品发布和实验性技术更新。", url: "https://x.com/joshwoodward" },
  { id: 42, name: "Ryo Lu", description: "Cursor 设计负责人，长期输出关于 AI 编程、软件设计的深度观点。", url: "https://x.com/ryolu_" },
  { id: 43, name: "Aditya Agarwal", description: "前 Dropbox CTO、Facebook 工程负责人，分享团队和技术扩展经验。", url: "https://x.com/adityaag" },
  { id: 44, name: "Cat Wu", description: "Claude Code 与 Cowork 产品负责人。", url: "https://x.com/_catwu" },
  { id: 45, name: "Madhu Guru", description: "Google Gemini、Veo、Nano Banana 产品负责人。", url: "https://x.com/realmadhuguru" },
  { id: 46, name: "Nan Yu", description: "Linear 产品负责人，分享产品思考、SaaS 实践和科技趋势评论。", url: "https://x.com/thenanyu" },
  { id: 47, name: "AI as Normal Technology", description: "分析 AI 如何成为日常技术和商业基础设施的一部分。", url: "https://www.normaltech.ai" },
  { id: 48, name: "Alex Kladov (matklad)", description: "rust-analyzer 创建者，撰写关于 Rust、IDE 架构、编译器设计和软件工程的文章。", url: "https://matklad.github.io" },
  { id: 49, name: "Amos Wenger", description: "以 Rust、系统内部原理、网络协议和 Linux 的超详细长文著称。", url: "https://fasterthanli.me" },
  { id: 50, name: "Andre Garzia", description: "撰写 Web 开发、编程实践和易用软件设计方面的文章。", url: "https://andregarzia.com" },
  { id: 51, name: "Andrej Karpathy", description: "分享深度学习洞察和教程。", url: "https://karpathy.bearblog.dev" },
  { id: 52, name: "Apple ML Research", description: "苹果机器学习研究发布，覆盖端侧 AI 和隐私保护 ML 技术。", url: "https://machinelearning.apple.com" },
  { id: 53, name: "Aral Balkan", description: "撰写数字隐私、监控资本主义和伦理去中心化技术方面的文章。", url: "https://ar.al" },
  { id: 54, name: "Asianometry", description: "深度分析半导体产业、亚洲经济和科技发展史。", url: "https://www.asianometry.com" },
  { id: 55, name: "Austin Henley", description: "软件工程研究者，撰写编程工具、开发者生产力和 AI 辅助编程方面的文章。", url: "https://austinhenley.com" },
  { id: 56, name: "Avery Pennarun", description: "Tailscale CEO，撰写网络、分布式系统、管理和软件架构哲学文章。", url: "https://apenwarr.ca" },
  { id: 57, name: "Ben Hoyt", description: "分享 Go、Python、系统编程和简洁高效软件方面的实用文章。", url: "https://benhoyt.com", feedUrl: "https://benhoyt.com/writings/rss.xml" },
  { id: 58, name: "Ben UI", description: "虚幻引擎、C++ 游戏编程和游戏开发工作流教程。", url: "https://benui.ca" },
  { id: 59, name: "Bert Hubert", description: "撰写网络协议、开源、欧洲科技政策和互联网基础设施方面的文章。", url: "https://berthub.eu" },
  { id: 60, name: "Bradford Morgan White", description: "通过研究文章记录复古软件、操作系统和个人电脑革命。", url: "https://abortretry.fail" },
  { id: 61, name: "Brian Krebs", description: "独立网络安全记者，以深入调查恶意软件、数据泄露和网络欺诈著称。", url: "https://krebsonsecurity.com" },
  { id: 62, name: "Hugging Face Blog", description: "开源模型、数据集、Transformers、推理基础设施和 AI 研究的官方更新。", url: "https://huggingface.co/blog", feedUrl: "https://huggingface.co/blog/feed.xml" },
  { id: 63, name: "Brook Bach", description: "通过长文探索技术、社会和文化的交汇点。", url: "https://brookbach.com" },
  { id: 64, name: "brr.fyi", description: "来自南极点和麦克默多站的一手记录，涵盖极端环境工程。", url: "https://brr.fyi" },
  { id: 65, name: "Cameron Kaiser", description: "复古计算、经典计算机修复和老硬件联网方面的详细文章。", url: "https://oldvcr.blogspot.com" },
  { id: 66, name: "Cloudflare Blog", description: "互联网基础设施、安全、边缘计算、网络性能和 AI 推理平台的技术更新。", url: "https://blog.cloudflare.com", feedUrl: "https://blog.cloudflare.com/rss/" },
  { id: 67, name: "Cerebralab", description: "分享机器学习实施、数据科学挑战和真实 AI 项目经验。", url: "https://blog.cerebralab.com" },
  { id: 68, name: "Chip Huyen", description: "ML 系统设计、MLOps 和实用 AI 工程洞察。", url: "https://huyenchip.com" },
  { id: 69, name: "Chips and Cheese", description: "深入剖析 AMD、Intel、Apple 和高通的 CPU、GPU 与微架构。", url: "https://chipsandcheese.com" },
  { id: 70, name: "Chris Siebenmann", description: "Linux、系统管理、邮件基础设施和网络运维实用经验。", url: "https://utcc.utoronto.ca/~cks/space/blog/", feedUrl: "https://utcc.utoronto.ca/~cks/space/blog/?atom" },
  { id: 71, name: "Cliff Biffle", description: "嵌入式 Rust、操作系统设计和可靠底层软件方面的深度技术文章。", url: "https://cliffle.com" },
  { id: 72, name: "Dan Abramov", description: "React 内部原理、JavaScript 心智模型和前端工程哲学。", url: "https://overreacted.io" },
  { id: 73, name: "Dan Luu", description: "对编程、计算机硬件、延迟和科技行业实践进行数据驱动分析。", url: "https://danluu.com" },
  { id: 74, name: "Dan Moore", description: "身份认证、开发者体验、技术写作和营销与工程交叉领域。", url: "https://www.mooreds.com/wordpress/" },
  { id: 75, name: "David Crawshaw", description: "软件工程实践、Go 编程和技术公司建设方面的文章。", url: "https://crawshaw.io" },
  { id: 76, name: "David Heinemeier Hansson (DHH)", description: "Ruby on Rails 创建者，倡导开发者幸福、开源和去云化。", url: "https://world.hey.com/dhh" },
  { id: 77, name: "David Rosenthal", description: "长期数据存储、去中心化批评、加密货币和信息保存挑战。", url: "https://blog.dshr.org" },
  { id: 78, name: "Derek Sivers", description: "关于创业、音乐、个人发展和有意识生活的简洁文章。", url: "https://sive.rs" },
  { id: 79, name: "Doug Brown", description: "记录硬件维修、逆向工程和复古电子设备修复项目。", url: "https://downtowndougbrown.com" },
  { id: 80, name: "Eliezer Yudkowsky", description: "AI 存在风险、理性和对齐理论方面的文章。", url: "https://www.lesswrong.com/users/eliezer_yudkowsky" },
  { id: 81, name: "Ethan Mollick (One Useful Thing)", description: "在工作和教育中高效使用 AI 的实用洞察。", url: "https://www.oneusefulthing.org" },
  { id: 82, name: "Fabricated Knowledge", description: "半导体产业、供应链和芯片市场的深度付费分析。", url: "https://www.fabricatedknowledge.com" },
  { id: 83, name: "Farnam Street", description: "心智模型、决策框架和终身学习方法论。", url: "https://fs.blog" },
  { id: 84, name: "First Round Review", description: "来自 First Round Capital 网络的实战创业建议和运营知识。", url: "https://review.firstround.com" },
  { id: 85, name: "Fly.io Blog", description: "分布式系统、边缘计算、基础设施部署和全球应用平台运营。", url: "https://fly.io/blog" },
  { id: 86, name: "Francesco Mazzoli", description: "Haskell、系统编程、计算数学基础和函数式编程模式。", url: "https://mazzo.li" },
  { id: 87, name: "Fred Hebert", description: "Erlang/OTP、分布式系统可靠性、可观测性和容错软件。", url: "https://ferd.ca" },
  { id: 88, name: "Fred Wilson (AVC)", description: "Union Square Ventures 联合创始人分享科技投资和创业生态思考。", url: "https://avc.com" },
  { id: 89, name: "Gary Marcus", description: "对 AI 炒作、进展和根本局限性的批判性分析。", url: "https://garymarcus.substack.com" },
  { id: 90, name: "Google DeepMind", description: "Google 旗下 AI 实验室的研究突破和技术进展。", url: "https://deepmind.google", feedUrl: "https://deepmind.google/blog/rss.xml" },
  { id: 91, name: "Google Research", description: "Google 最新研究发布，覆盖 AI、系统和计算科学。", url: "https://blog.research.google", feedUrl: "https://blog.research.google/feeds/posts/default?alt=rss" },
  { id: 92, name: "GitHub AI & ML", description: "GitHub 官方发布 AI coding、Copilot、开发者工具和机器学习工程实践。", url: "https://github.blog/ai-and-ml/", feedUrl: "https://github.blog/ai-and-ml/feed/" },
  { id: 93, name: "Gregory Szorc", description: "构建系统、Python 打包、Rust 工具链和软件分发复杂性。", url: "https://gregoryszorc.com" },
  { id: 94, name: "Sequoia Capital", description: "从顶级风险投资视角分析 AI、公司建设、市场演化和技术商业化。", url: "https://sequoiacap.com", feedUrl: "https://sequoiacap.com/feed/" },
  { id: 95, name: "Gwern Branwen", description: "AI 规模定律、心理学、统计学、决策理论和技术预测长文。", url: "https://gwern.net" },
  { id: 96, name: "Henrik Karlsson", description: "关于思考、写作、人际关系和智识生活的文章。", url: "https://www.henrikkarlsson.xyz" },
  { id: 97, name: "J. B. Crawford", description: "探索电信网络、互联网交换中心、计算历史和政府技术系统。", url: "https://computer.rip" },
  { id: 98, name: "Jack Clark (Import AI)", description: "Anthropic 联合创始人的每周 AI 新闻摘要，覆盖政策和研究动态。", url: "https://importai.substack.com" },
  { id: 99, name: "Google Developers Blog", description: "Google 开发者生态、AI APIs、Gemini、Cloud 和工程工具的官方发布。", url: "https://developers.googleblog.com", feedUrl: "https://developers.googleblog.com/feeds/posts/default?alt=rss" },
  { id: 100, name: "Jamie Brandon", description: "编程语言设计、数据库内部原理、编译器和开发工具。", url: "https://www.scattered-thoughts.net" },
  { id: 101, name: "Jay Alammar", description: "用可视化和交互方式讲解 NLP、Transformer 和大语言模型。", url: "https://jalammar.github.io" },
  { id: 102, name: "JeanHeyd Meneide", description: "编程语言演进、文本编码和系统语言未来。", url: "https://thephd.dev" },
  { id: 103, name: "Jeff Geerling", description: "树莓派、家庭自动化、开源基础设施和 Linux 系统。", url: "https://www.jeffgeerling.com" },
  { id: 104, name: "Jeremy Kun", description: "数学、算法和实用编程交叉点的文章。", url: "https://jeremykun.com" },
  { id: 105, name: "Jimmy Maher (The Digital Antiquarian)", description: "计算机娱乐、交互式小说和电子游戏演变历史。", url: "https://www.filfre.net" },
  { id: 106, name: "Joel Spolsky", description: "软件管理、招聘和产品开发方面的经典技术写作。", url: "https://www.joelonsoftware.com" },
  { id: 107, name: "John Graham-Cumming", description: "密码学、编程挑战、复古硬件修复和互联网基础设施。", url: "https://blog.jgc.org" },
  { id: 108, name: "Johnny Noble (Johnny.Decimal)", description: "基于数字的文件、笔记和项目组织系统。", url: "https://johnnydecimal.com" },
  { id: 109, name: "Julia Evans", description: "用清晰写作和插图解释 Linux、DNS、调试和网络。", url: "https://jvns.ca" },
  { id: 110, name: "Julio Merino", description: "构建系统、测试实践、FreeBSD 和大规模软件工程。", url: "https://jmmv.dev" },
  { id: 111, name: "Kaspar Etter", description: "密码学、电子邮件协议和网络的结构化交互式讲解。", url: "https://explained-from-first-principles.com" },
  { id: 112, name: "Ken Shirriff", description: "从硅片层面逆向工程历史处理器和电路。", url: "https://www.righto.com" },
  { id: 113, name: "Kevin Chen", description: "安全漏洞、技术系统和计算机科学主题的深度分析。", url: "https://kevinchen.co" },
  { id: 114, name: "Leon Trolski", description: "Python、PostgreSQL、Web 开发和简洁编程方案。", url: "https://leontrolski.github.io" },
  { id: 115, name: "Lilian Weng (Lil'Log)", description: "全面且严谨的机器学习技术综述。", url: "https://lilianweng.github.io" },
  { id: 116, name: "Mark Dominus (The Universe of Discourse)", description: "关于编程语言、数学、语言学和书评的文章。", url: "https://blog.plover.com" },
  { id: 117, name: "Martin Fowler", description: "重构、设计模式、敏捷方法论和软件架构。", url: "https://martinfowler.com", feedUrl: "https://martinfowler.com/feed.atom" },
  { id: 118, name: "Mat Duggan", description: "技术文化、基础设施工程和科技行业人文面的坦诚观点。", url: "https://matduggan.com" },
  { id: 119, name: "Max Bernstein", description: "编译器、编程语言实现、性能优化和解释器内部原理。", url: "https://bernsteinbear.com" },
  { id: 120, name: "Max Read", description: "以文化批评和评论报道技术、媒体、互联网文化和社会。", url: "https://maxread.substack.com" },
  { id: 121, name: "Michael Lynch", description: "独立软件创业，包括详细收入报告和家庭实验室项目。", url: "https://mtlynch.io" },
  { id: 122, name: "Michal Zalewski", description: "电子学、硬件黑客和安全工程方面的文章。", url: "https://lcamtuf.substack.com" },
  { id: 123, name: "Microsoft Research", description: "微软研究院在 AI、系统和人机交互领域的研究发布。", url: "https://www.microsoft.com/en-us/research/blog" },
  { id: 124, name: "Morgan Housel", description: "行为金融智慧和投资心理学随笔。", url: "https://collabfund.com/blog" },
  { id: 125, name: "Musings on Markets", description: "Damodaran 教授的估值分析、市场评论和公司金融洞察。", url: "https://aswathdamodaran.blogspot.com" },
  { id: 126, name: "Naval Ravikant", description: "关于财富创造、幸福和创业的哲学思考。", url: "https://nav.al" },
  { id: 127, name: "Neil Gaiman", description: "关于写作技艺、讲故事、奇幻文学和创作过程的思考。", url: "https://www.neilgaiman.com", feedUrl: "https://www.neilgaiman.com/feed/journal/" },
  { id: 128, name: "Nikhil Suresh (Ludic)", description: "对科技行业弊病、软件工程文化和组织失败的犀利点评。", url: "https://ludic.mataroa.blog" },
  { id: 129, name: "Nikita Prokopov", description: "UI 设计、开发工具、Clojure 和软件设计观点。", url: "https://tonsky.me" },
  { id: 130, name: "NVIDIA AI Blog", description: "NVIDIA 的 AI 研究更新、GPU 计算进展和深度学习突破。", url: "https://blogs.nvidia.com" },
  { id: 131, name: "OpenAI Blog", description: "OpenAI 官方发布模型更新、研究进展和 AI 安全动态。", url: "https://openai.com/news", feedUrl: "https://openai.com/news/rss.xml" },
  { id: 132, name: "Patrick McKenzie (patio11)", description: "SaaS 定价、A/B 测试、转化优化、薪资谈判和软件商业。", url: "https://kalzumeus.com" },
  { id: 133, name: "Paul Graham", description: "关于创业、编程和独立思考的经典文章。", url: "https://paulgraham.com" },
  { id: 134, name: "Raymond Chen (The Old New Thing)", description: "Windows API 内部原理、Win32 编程历史和设计决策。", url: "https://devblogs.microsoft.com/oldnewthing" },
  { id: 135, name: "Salvatore Sanfilippo (antirez)", description: "数据库设计、数据结构、系统架构和简洁高效软件。", url: "https://antirez.com", feedUrl: "https://antirez.com/rss" },
  { id: 136, name: "Sam Altman", description: "关于 AI 进展、创业和科技未来的思考。", url: "https://blog.samaltman.com" },
  { id: 137, name: "Sean Goedecke", description: "编程技艺、职业发展、写作和技术个人项目。", url: "https://seangoedecke.com" },
  { id: 138, name: "Sebastian Raschka", description: "ML 研究者的实战教程，聚焦深度学习和大语言模型。", url: "https://magazine.sebastianraschka.com" },
  { id: 139, name: "SemiAnalysis", description: "半导体产业深度付费分析，覆盖芯片、AI 硬件和市场情报。", url: "https://semianalysis.com" },
  { id: 140, name: "Simon Willison", description: "大语言模型、提示工程、数据新闻和开源开发工具。", url: "https://simonwillison.net" },
  { id: 141, name: "Steph Ango", description: "设计哲学、技术趋势、生产力和知识工具未来。", url: "https://stephango.com" },
  { id: 142, name: "MIT News — Artificial Intelligence", description: "MIT 官方发布 AI、机器人、计算科学与前沿研究成果。", url: "https://news.mit.edu/topic/artificial-intelligence2", feedUrl: "https://news.mit.edu/rss/topic/artificial-intelligence2" },
  { id: 143, name: "Stratechery (Ben Thompson)", description: "用聚合理论和平台经济学视角分析科技战略。", url: "https://stratechery.com" },
  { id: 144, name: "Tanel Poder", description: "数据库和系统性能、Oracle、Linux 调优和容器内部分析。", url: "https://tanelpoder.com" },
  { id: 145, name: "Taylor Town", description: "Web 开发、编程哲学和技术实验想法。", url: "https://taylor.town" },
  { id: 146, name: "The Gradient", description: "以通俗易懂的方式连接 AI 研究和社会影响。", url: "https://thegradient.pub" },
  { id: 147, name: "Thorsten Ball", description: "编程语言、编译器、Go 和软件开发技艺。", url: "https://registerspill.thorstenball.com" },
  { id: 148, name: "Tom MacWright", description: "JavaScript 生态、地图与地理空间技术和 Web 开发哲学。", url: "https://macwright.com" },
  { id: 149, name: "Tom Tontinton", description: "Rust、数据库内部原理、系统编程和高性能基础设施。", url: "https://tontinton.com" },
  { id: 150, name: "Tomasz Tunguz", description: "数据驱动的 SaaS 指标分析、创业基准和风投趋势洞察。", url: "https://tomtunguz.com" },
  { id: 151, name: "Tristan Hume", description: "性能优化、开发者工具、眼动追踪技术和实用编程技巧。", url: "https://thume.ca" },
  { id: 152, name: "Unix Sheikh", description: "倡导简洁、Unix 哲学、开源工具，并批评现代 Web 开发复杂性。", url: "https://unixsheikh.com" },
  { id: 153, name: "Vicki Boykis", description: "ML 工程、数据管道、推荐系统和 AI 数据工作的人文面。", url: "https://vickiboykis.com" },
  { id: 154, name: "Xe Iaso", description: "Nix、NixOS、AI 实验、Linux 系统和编程。", url: "https://xeiaso.net" },
  { id: 155, name: "xorvoid", description: "系统编程、编译器构建、底层优化和第一性原理软件构建。", url: "https://xorvoid.com" },
  { id: 156, name: "Yossi Kreinin", description: "编程实践、硬件工程、C++ 复杂性以及理论与实践差距。", url: "https://yosefk.com" },
  { id: 157, name: "Zvi Mowshowitz", description: "全面的每周 AI 新闻分析，结合理性主义评论和政策视角。", url: "https://thezvi.substack.com" },
  { id: 158, name: "Hacker News", description: "Hacker News 每日高质量 Best stories。", url: "https://news.ycombinator.com/best" },
  { id: 159, name: "Product Hunt", description: "Product Hunt 每日 Top 新产品。", url: "https://www.producthunt.com/" },
];
